version: "3.8"

services:
  drs-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - APP_ENV=development
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload